import = [
  "~/.config/alacritty/tokyonight-storm.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[keyboard]
bindings = [
  # { key = "Right", mods = "Alt", chars = "\u001BF" },
  # { key = "Left",  mods = "Alt", chars = "\u001BB" },
  # { key = "Right", mods = "Super", chars = "\u0005F" },  # Move to end of line
  # { key = "Left",  mods = "Super", chars = "\u0001B" },  # Move to beginning of line
]

[cursor]
blink_interval = 500
blink_timeout = 5
unfocused_hollow = false

[cursor.style]
blinking = "Off"
shape = "Block"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
program = "/bin/zsh"

[font]
size = 18 

[font.bold]
# family = "MesloLGS Nerd Font Mono"
style = "Bold"
family = "JetBrainsMono Nerd Font Mono"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[window]
option_as_alt = "Both"
# decorations = "None"

[window.padding]
x = 4
y = 1
