import = [
  "~/.config/alacritty/one_dark.toml"
]

[env]
TERM = "xterm-256color"

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
  # { key = "Right", mods = "Super", chars = "\u0005F" },  # Move to end of line
  # { key = "Left",  mods = "Super", chars = "\u0001B" },  # Move to beginning of line
]

[font]
size = 16

[font.bold]
# family = "MesloLGS Nerd Font Mono"
style = "Bold"
family = "JetBrainsMono Nerd Font Mono"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[window.padding]
x = 10
y = 1
